### Import Libraries

In [4]:
import pandas as pd

### Load the Dataset

In [5]:
file_path = r"C:\Users\HP\Desktop\Infotact Internship\AI4I_Predictive.csv"

In [6]:
df = pd.read_csv(file_path)

In [7]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

### Shape of the Data

In [8]:
df.shape

(10000, 14)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

The above information says that there is no missing values.

### select sensor features

In [2]:
sensor_columns = ["Air temperature [K]",
                  "Process temperature [K]",
                  "Rotational speed [rpm]",
                  "Torque [Nm]",
                  "Tool wear [min]"]

### create rolling features

In [10]:
window_size = 10

for col in sensor_columns:

    df[f'{col}_rolling_mean'] = df[col].rolling(window=window_size).mean()
    df[f'{col}_rolling_std'] = df[col].rolling(window=window_size).std()
    df[f'{col}_rolling_var'] = df[col].rolling(window=window_size).var()

In [11]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,Process temperature [K]_rolling_var,Rotational speed [rpm]_rolling_mean,Rotational speed [rpm]_rolling_std,Rotational speed [rpm]_rolling_var,Torque [Nm]_rolling_mean,Torque [Nm]_rolling_std,Torque [Nm]_rolling_var,Tool wear [min]_rolling_mean,Tool wear [min]_rolling_std,Tool wear [min]_rolling_var
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.tail()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,Process temperature [K]_rolling_var,Rotational speed [rpm]_rolling_mean,Rotational speed [rpm]_rolling_std,Rotational speed [rpm]_rolling_var,Torque [Nm]_rolling_mean,Torque [Nm]_rolling_std,Torque [Nm]_rolling_var,Tool wear [min]_rolling_mean,Tool wear [min]_rolling_std,Tool wear [min]_rolling_var
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,...,0.011222,1583.2,131.944264,17409.288889,34.29,7.490357,56.105444,68.2,97.947605,9593.733333
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,...,0.009444,1595.7,129.827278,16855.122222,33.24,6.959917,48.440444,49.2,85.692992,7343.288889
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,...,0.009444,1610.2,125.991887,15873.955556,32.87,6.829031,46.635667,30.4,64.496684,4159.822222
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,...,0.013778,1573.9,126.805582,16079.655556,35.31,7.656290,58.618778,11.6,8.099383,65.600000
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,...,0.019556,1566.2,128.916683,16619.511111,36.01,7.761221,60.236556,14.6,8.846845,78.266667

### Handle initial Nan

In [13]:
df.bfill(inplace=True)

In [14]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,Process temperature [K]_rolling_var,Rotational speed [rpm]_rolling_mean,Rotational speed [rpm]_rolling_std,Rotational speed [rpm]_rolling_var,Torque [Nm]_rolling_mean,Torque [Nm]_rolling_std,Torque [Nm]_rolling_var,Tool wear [min]_rolling_mean,Tool wear [min]_rolling_std,Tool wear [min]_rolling_var
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,...,0.018222,1521.6,113.060652,12782.711111,39.91,6.826655,46.603222,10.4,6.834553,46.711111
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,...,0.018222,1521.6,113.060652,12782.711111,39.91,6.826655,46.603222,10.4,6.834553,46.711111
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,...,0.018222,1521.6,113.060652,12782.711111,39.91,6.826655,46.603222,10.4,6.834553,46.711111
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,...,0.018222,1521.6,113.060652,12782.711111,39.91,6.826655,46.603222,10.4,6.834553,46.711111
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,...,0.018222,1521.6,113.060652,12782.711111,39.91,6.826655,46.603222,10.4,6.834553,46.711111

In [15]:
df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF',
       'Air temperature [K]_rolling_mean', 'Air temperature [K]_rolling_std',
       'Air temperature [K]_rolling_var',
       'Process temperature [K]_rolling_mean',
       'Process temperature [K]_rolling_std',
       'Process temperature [K]_rolling_var',
       'Rotational speed [rpm]_rolling_mean',
       'Rotational speed [rpm]_rolling_std',
       'Rotational speed [rpm]_rolling_var', 'Torque [Nm]_rolling_mean',
       'Torque [Nm]_rolling_std', 'Torque [Nm]_rolling_var',
       'Tool wear [min]_rolling_mean', 'Tool wear [min]_rolling_std',
       'Tool wear [min]_rolling_var'],
      dtype='object')

### Verify new columns

In [16]:
new_cols = [c for c in df.columns if 'rolling' in c]
new_cols

['Air temperature [K]_rolling_mean',
 'Air temperature [K]_rolling_std',
 'Air temperature [K]_rolling_var',
 'Process temperature [K]_rolling_mean',
 'Process temperature [K]_rolling_std',
 'Process temperature [K]_rolling_var',
 'Rotational speed [rpm]_rolling_mean',
 'Rotational speed [rpm]_rolling_std',
 'Rotational speed [rpm]_rolling_var',
 'Torque [Nm]_rolling_mean',
 'Torque [Nm]_rolling_std',
 'Torque [Nm]_rolling_var',
 'Tool wear [min]_rolling_mean',
 'Tool wear [min]_rolling_std',
 'Tool wear [min]_rolling_var']

In [17]:
df.to_csv("ai4i_feature_engineered.csv", index=False)

In [18]:
import os
print(os.getcwd())

c:\Users\HP\Desktop\PredictX\notebooks